spring:
  application:
    name: consumer2
server:
  port: 2346
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:1111/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
feign.hystrix.enabled: true