server:
  port: 2000
spring:
  application:
    name: eurekaclient
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:1111/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

