spring:
  application:
    name: consumerservice
  zipkin:
    base-url: http://localhost:9411
server:
  port: 2345
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
