spring:
  application:
    name: providerservice-v1
server:
  port: 5679
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:1111/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
