spring:
  application:
    name: providerservice-v1
  zipkin:
    base-url: http://localhost:9411
server:
  port: 7903
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:1111/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
