
server:
  port: 1111
eureka:
  instance:
    hostname: localhost
  client:
    healthcheck:
      enabled: true

    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://user:password@${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: eurekaserver
security:
  basic:
    enabled: true
  user:
    name: user
    password: password