spring:
  application:
    name: microservice-zuul-sidecar
server:
  port: 6666
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:1111/eureka/
sidecar:
  port: 8000
  health-uri: http://localhost:8000/health.json