server:
  port: 6677
spring:
  application:
    name: config-server-eurekaserver
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/marrymayun/config-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/







